language: rust

rust:
- stable
- beta
- nightly
- 1.28.0

script:
  - cargo build
  - cargo build --release
  - cargo build --no-default-features
  - cargo build --release --no-default-features
  - cargo test
  - cargo test --release

matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true